# Generated by Django 5.2.15 on 2026-06-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_discipline_end_date_discipline_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('GREEN', 'In Progress'), ('YELLOW', 'Pending'), ('RED', 'Completed')], max_length=20),
        ),
    ]
