# Generated by Django 5.2.15 on 2026-06-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('pmc', models.CharField(max_length=200)),
                ('contractor', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('target_completion', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
